name: Deploy to Glitch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Deploy to Glitch
      run: |
        curl -X POST https://api.glitch.com/projects/{discord-umu-2525-1}/git/import \
          -d "{\"remoteUrl\":\"https://api.glitch.com/git/{discord-umu-2525-1}\"}" \
          -H "Authorization: Bearer ${GLITCH_TOKEN}" \
          -H "Content-Type: application/json"
      env:
        GLITCH_TOKEN: ${{ secrets.GLITCH_TOKEN }}
